{% set name = "jaraco.stream" %}
{% set version = "1.2" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "2b56514708224864d93b8a6e916c02ae7ae4ce822f05946704719bb294971a1b" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools
    - setuptools_scm >=1.15.0

  run:
    - python
    - six

test:
  imports:
    - jaraco
    - jaraco.stream

about:
  home: https://github.com/jaraco/jaraco.stream
  # license_file: jaraco doesn't include license files - see https://github.com/jaraco/skeleton/issues/1
  license: MIT
  license_family: MIT
  summary: 'Routines for dealing with data streams'
  dev_url: https://github.com/jaraco/jaraco.stream

extra:
  recipe-maintainers:
    - pmlandwehr
