{% set name = "jaraco.stream" %}
{% set version = "2.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "c2e9d507d8cf04a3ff916b57eaf46bacb8a9f8895b55ead853de9c47b8f5daa4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  build:
    - python >=3.6
    - pip
    - setuptools_scm >=1.15.0

  run:
    - python >=3.6
    - six

test:
  imports:
    - jaraco
    - jaraco.stream

about:
  home: https://github.com/jaraco/jaraco.stream
  # license_file: jaraco doesn't include license files - see https://github.com/jaraco/skeleton/issues/1
  license: MIT
  license_family: MIT
  summary: 'Routines for dealing with data streams'
  dev_url: https://github.com/jaraco/jaraco.stream

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
