{% set name = "jaraco.stream" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaraco_stream-{{ version }}.tar.gz
  sha256: e2bc5028e721ed2cc852b96ec9a33f2b7664e9b2dbf87eefbe617d126641934b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=1.15.0

  run:
    - python >={{ python_min }}
    - six
    - more-itertools

test:
  imports:
    - jaraco
    - jaraco.stream
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jaraco/jaraco.stream
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Routines for dealing with data streams
  dev_url: https://github.com/jaraco/jaraco.stream

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
