travis:
  secure:
    BINSTAR_TOKEN: k6XCc2wje0HEWJOw+WFqwqjxhuv5niMFimMrWuRjYl8VhtQ8aJ8pKgyPpwxpwudStywj4H+BlJ2YhQIpSqNW8owtlOy45h8IIBG2jS0bplhVPv6XxHujIuYURHKReeKqR0KFfggfT1Bm0b7Yhf1VtemRaOJdui1Be8lP2Ls1OwPY/HEST4Pc/DLlRHlZjJvIrmdMCTP8nZ5mRL59QowGpXMinCQaLQ8N3OsbKmNhsVnW6jIxw9May9YFb6PaW4CTCc/Q2lD/CxO01YIlshIOeUtAw6Bg2MCL6v2AD4qSlaytBrPS9PjV+qS0wZtNsfTN2as850lL73TAxZA6qznfXQgaS3kbRIMFiq5MAFj4xct8bhwz8cWUjxKCT17ZrXaCCHASbon+pO+ipznmXi1cAqFSXSkdxDr+buJJGJ6cvAAtGsZy6Yjk88EEG2JVivkJw5vXsQiRpHfFpK2uzU1mUXmEqIUXFvG80C1TR/9XexVLgOVp7X4b06YWvKVuf1TcMEkLPuEKAe+M8xUraB80ghJ3TGzhgigUy9b1tIsRtXMzNLKozOht4SbULXXb6WD6/OFO3qkMnSEpLp6rOmoDoxBIVnTdSsm6ipWyXHnhEw4AQDb/hFYHX4SJ9gWaO4EwbxkPfuTbNLMfsbwz+t7ZA1RI8ZytNnvFYbn/zuNHlVY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
