travis:
  secure:
    BINSTAR_TOKEN: CY7a9VRqs2XgIlyhag1xEoPVfcDetyECgoYLoDi6dJyg6uSyLbg2vXmopc9alkXHkrqDu3pk95kirbj87zsTdQDvH/zwqZwTx1KKjldBIHFJPzjlWN8VZjVerG6nib5faPV9QRKFp7e6K8GeIgLhuunKi1Sb01sqh/b+tKiOI/S9gpTt2QMKQ8ULH1wJJ4Eubi7Sbup22CPbuil3/7fyEhKu6a5MS6VUVECukGqpL5rG0PwsWTfnbY7If8V6ScsjvvYQLW2Zs0qsymYZW74nDLawDHDU2PZ+t+zFkxdHKwVqjI7Gm72F1ra7pLciYd2qE0FUnDuarNWgqtai7NBdjIzV6E2JmGNCgulbR6FaOvluv4m0k17eAdsvyjjc+x0JgxYqkdoNYnHuPdmUSj8z6uqRXAVkTaxcgIorD9guWq5pNuOZ7Iuyv9Q7ofVOFujWSy/ps4UDKoPe9h9cN384p6j+3QwQn0DNnl7UvRBZz33OA3gd5UC7aLaTxlCK/jBRCp2quRK57OQv1wodoWPEV+WeWCE5tX6+LqBS4AfQOKnlgUrq9Hyvzz/Q08tsFnJLnnrFSkNWsqT5AX+KZNeHOYd4fu4kbxqqYwN5pbhxQQ/ON2bVFACWcVG8epjD5igzsWzDMrr+/IfeG6KQF+dnHDMDyoy2Y0Hb/IHKW3BWvww=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
